services:
  - type: web
    name: gym
    env: node
    plan: free
    buildCommand: npm ci && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'
      - key: DB_INIT_ON_BOOT
        value: 'false'
      - key: ALLOW_SCHEMA_RESET
        value: 'false'
      - key: SESSION_SECRET
        sync: false
      - key: SESSION_TIMEOUT
        sync: false
      - key: CORS_ORIGIN
        sync: false
      # Neon Database Connection
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: 'true'
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: 'false'
    autoDeploy: true
    branch: main
